accent: 0xC27C0E
support_discord: https://discord.com/invite/EhGjg2drSQ
sql_file: ./rewrite/utils/hanjadic.sqlite
avatar: https://i.imgur.com/v95B0db.jpg
korean_flag: ğŸ‡°ğŸ‡·
english_flag: ğŸ´ó §ó ¢ó ¥ó ®ó §ó ¿
